# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# User Settings
# This is where you put your own settings as this will not be touched during update 
# if the upgrade.sh is used.

# refer to Hyprland wiki for more info https://wiki.hyprland.org/Configuring/Variables/
# NOTE: some settings are in ~/.config/hypr/UserConfigs/UserDecorAnimations.conf
#
# Look on ~/.config/hypr/configs/SystemSettings.conf to know how to modify this

# --- Tablet / pen devices mapped to external monitor ---
device {
    name = wacom-cintiq-16-pen
    output = HDMI-A-1
}
device {
    name = deco-lw-pen
    output = HDMI-A-1
}
device {
    name = deco-lw-mouse
    output = HDMI-A-1
}
device {
    name = xp-pen-mouse
    output = HDMI-A-1
}
device {
    name = xp-pen-pen
    output = HDMI-A-1
}
device {
    name = xp-pen-eraser
    output = HDMI-A-1
}

# --- Scrolling layout settings ---
scrolling {
  column_width = 0.5
  fullscreen_on_one_column = true
  focus_fit_method = 1              # 0 = center, 1 = fit
  follow_focus = true
  follow_min_visible = 0.4
  explicit_column_widths = 0.333, 0.5, 0.667, 1.0
  direction = right
}

# --- Scrolling layout settings ---
scrolling {
  column_width = 0.5
  fullscreen_on_one_column = true
  focus_fit_method = 1              # 0 = center, 1 = fit
  follow_focus = true
  follow_min_visible = 0.4
  explicit_column_widths = 0.333, 0.5, 0.667, 1.0
  direction = right
}
